apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: default
  labels:
    deploymentName: buyer-service
spec:
  scaleTargetRef:
    name: buyer-service
  minReplicaCount: 0
  maxReplicaCount:  4 # (3)
  pollingInterval: 30
  advanced:
    horizontalPodAutoscalerConfig: # (4)
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60        

        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60  
  
  triggers:
    - type: kafka
      metadata:
        consumerGroup: payex-local-group
        bootstrapServers: 10.122.0.23:9092:9092
        topic: payex.ledger
        lagThreshold: "10"
        offsetRestPolicy: earliest