apiVersion: v1
kind: Service
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: producer-deployment
